### ISSUE TITLE
报警器类设备的测试报警

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#10]
**问题描述**
报警器类设备，点击APP中的测试报警，网关和设备都无反应，APP也不会收到推送，存在通讯稳定性问题

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**

**Comment by xiaoyang432** [comment]
问题同#50，不用重复提交，"ver-...20190725..."之后的固件版本，已经解决，3mS不间断广播持续10S。
