### ISSUE TITLE
从推送到APP的入口问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#12]
**问题描述**
APP切换至后台运行触发安防报警器，点击通知栏的推送后，会切换到APP中，但是此时APP界面变暗，APP无法操作；若触发时APP是桌面运行状态，切回主界面点击通知，会回到APP界面，此时不存在前面提到的问题
一加手机存在问题，其他的安卓手机没有出现。
**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/61694002-2673c680-ad63-11e9-8c4b-734499286301.png)

**Comment by tracyhenryduck2** [comment]
1.008版本已解决

**Comment by tracyhenryduck2** [comment]
@fengzehua5

**Comment by fengzehua5** [comment]
已解决
