### ISSUE TITLE
网关名称字符上限

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#13]
**问题描述**
前面已经改为最多20个字符，但是输入中文的话，名称会和后面的场景切换，网关状态重叠，建议网关字符上限再短一些

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60561159-2f393400-9d85-11e9-8f3b-7a6cd14410c1.png)

**Comment by tracyhenryduck2** [comment]
最新版本已经有上线控制了，最多20个字符
