### ISSUE TITLE
配网页面动图

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#15]
**问题描述**
配网页面动图修改为与网关一致，不要再沿用以前的188系统

改成：网关上电五秒后，长按网关按钮直到网关发出“嘀嘀”两声松开按钮，
                                        等待蓝灯闪烁后，点击下一步

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**

**Comment by ju0014** [comment]
已修复

**Comment by fengzehua5** [comment]
已解决
