### ISSUE TITLE
网关设备页同步

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#16]
**问题描述**
网关的设备页面没有设备同步功能，目前刷新入口只有主界面有，应该增加刷新入口，网关的其他界面也需要

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
ios已解决，1.6版本@fengzehua5

**Comment by fengzehua5** [comment]
iOS已解决

**Comment by tracyhenryduck2** [comment]
android 1.009将修复这个bug @fengzehua5

**Comment by fengzehua5** [comment]
已解决
