### ISSUE TITLE
网关绑定

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#18]
**问题描述**
已绑定的网关无法被其他网关绑定。网关无法被直接抢绑，抢绑时首次提示为“网关被XXXX绑定”，后面都提示绑定失败。这个需要统一一种说法比较好。

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**

**Comment by qiubaochun** [comment]
问题同#62
