### ISSUE TITLE
主页面优化

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#27]
**问题描述**
在主页面，添加在一个网关下多个设备后下拉到底部，接着上拉不能回到顶部，出现的是自动同步设备页防呆，需再次上拉才会实现回到顶部。

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**

**Comment by ju0014** [comment]
已修复

**Comment by fengzehua5** [comment]
已解决
