### ISSUE TITLE
绑定界面优化

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#32]
**问题描述**
绑定已经被绑走的网关，当显示设备已经连入WiFi后，点击绑定，屏幕中间的防呆标识持续时间太长，将近一分钟左右才会提示无法绑定

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**

**Comment by qiubaochun** [comment]
重复测试没有此问题
