### ISSUE TITLE
登录界面

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#34]
**问题描述**
登录界面的账号最多保存三条，iOS的账号后面应该有可以将登录过的账号清除的按钮；Android版点击账号后面的清除按钮，会弹出登录过得账号的列表，有*号保护隐私，但是随便点击一个就会把完整账号显示在账号栏，有些自相矛盾的意味；iOS不论在账号栏还是下拉列表，账号都不会完全显示

**测试环境**
1. 固件版本号: 
2. app版本号:FamilyWell+1.0   1.004
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
阿里的sdk把控件封装死了，所以改不了这个控件

**Comment by tracyhenryduck2** [comment]
@fengzehua5
