### ISSUE TITLE
验证码重复

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#35]
**问题描述**
重置密码时，若第一次输入验证码失误，再次获取到的验证码两次应不同，Android和iOS都存在这样的问题

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0   1.004
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
跟平台服务器设计有关。

**Comment by tracyhenryduck2** [comment]
@fengzehua5

**Comment by tracyhenryduck2** [comment]
这个跟服务器的设置有关，20分钟内获取验证码都是一样的。我跟平台工程师确认过了。可以关闭了 @fengzehua5
