### ISSUE TITLE
配网页面

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#37]
**问题描述**
配网页面点击输入密码栏，密码栏会到屏幕顶部，配网页面UI需优化；配网时，没有“记住密码”按钮；配网完成无重命名对话框

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60565335-bee6de80-9d95-11e9-8f78-8d67228c60d5.png)
![image](https://user-images.githubusercontent.com/52404201/60565342-c4442900-9d95-11e9-9382-a9073e895344.png)
![image](https://user-images.githubusercontent.com/52404201/60565346-ca3a0a00-9d95-11e9-9577-c9a84b075f12.png)

**Comment by tracyhenryduck2** [comment]
已解决，配网页面已重新设计。 @fengzehua5
