### ISSUE TITLE
加入240后的问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#38]
**问题描述**
添加240后，不可以在首页查看温湿度，且一直显示设备离线，设备列表中，温湿度后面会有一个和网关场景一样功能的按钮，但是点击会闪退

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60565444-37e63600-9d96-11e9-919e-da2f6ba54b35.png)

**Comment by tracyhenryduck2** [comment]
@fengzehua5 已解决
