### ISSUE TITLE
网关的设备界面

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#39]
**问题描述**
网关的设备界面没有刷新的功能，进入子设备界面，只能上拉出手机的功能栏，设备告警记录按钮不可以上拉

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
已解决 @fengzehua5
