### ISSUE TITLE
场景描述

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#40]
**问题描述**
网关界面里的情景要改为场景，情景模式要改为自动化

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
已解决 @fengzehua5

**Comment by fengzehua5** [comment]
还是存在一些瑕疵
![image](https://user-images.githubusercontent.com/52404201/61094633-8bd1d880-a482-11e9-95e5-094c4fd56943.png)

**Comment by fengzehua5** [comment]
已解决

**Comment by fengzehua5** [comment]
iOS已完成，Android还需修改
![image](https://user-images.githubusercontent.com/52404201/61348908-d5606000-a894-11e9-9e1d-5d08807dc1f9.png)

**Comment by ju0014** [comment]
已修复

**Comment by fengzehua5** [comment]
已解决
