### ISSUE TITLE
定时切换场景的同步问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#42]
**问题描述**
可以定时自动切换场景，但是网关可以切换，APP设备页中网关状态和网关场景页状态无变化

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**

**Comment by fengzehua5** [comment]
固件版本号: ver-1.0.1-20190712.0837
app版本号:FamilyWell+1.1
![image](https://user-images.githubusercontent.com/52404201/61104672-cdc24500-a4a9-11e9-9c64-ab21a81ad49d.png)
![image](https://user-images.githubusercontent.com/52404201/61104681-d4e95300-a4a9-11e9-9ce5-51d46dbacf16.png)

**Comment by tracyhenryduck2** [comment]
@fengzehua5 1.5v版本已解决这个问题，已经可以下载了

**Comment by fengzehua5** [comment]
手动刷新后解决
