### ISSUE TITLE
网关场景界面优化

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#43]
**问题描述**
网关页内的添加场景按钮位置需调整，此按钮会挡住一些场景的选中按钮

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60565970-17b77680-9d98-11e9-8930-069309c3cdd7.png)

**Comment by tracyhenryduck2** [comment]
已解决，布局与安卓一致

**Comment by tracyhenryduck2** [comment]
@fengzehua5
