### ISSUE TITLE
设备添加自动化问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#44]
**问题描述**
门磁无法添加自动化，温湿度计显示离线，但是可以添加，设置完成后点击自动化条目会提示“有设备被删除”无法对其进行修改（其实并没有删除任何设备，只是设备显示的离线状态有误）；自动化删除只支持左滑

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60566611-f8214d80-9d99-11e9-9a46-324826291f4a.png)

**Comment by fengzehua5** [comment]
新发布的测试版本没有了上述问题，自动化删除只支持左滑
1. 固件版本号: ver-1.0.1-20190712.0837
2. app版本号:FamilyWell+1.1

**Comment by tracyhenryduck2** [comment]
已解决

**Comment by tracyhenryduck2** [comment]
@fengzehua5
