### ISSUE TITLE
设备页面优化

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#46]
**问题描述**
网关页的设备长按无反应，首页设备页设备长按只可以删除设备；有时进入APP后，首页网关后面的场景切换按钮会消失

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60566972-2b181100-9d9b-11e9-8067-ec1e2b3bff44.png)

**Comment by tracyhenryduck2** [comment]
消失的问题已解决；
另外删除操作还没有，之后网关页的删除都会改成长按删除

**Comment by tracyhenryduck2** [comment]
@fengzehua5
