### ISSUE TITLE
PIR添加后问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#47]
**问题描述**
添加同一个GS300，FamilyWell会很准确的显示它的触发和恢复，FamilyWell+不会

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**

**Comment by xiaoyang432** [comment]
老款PIR与阿里网关通讯 时序有点问题，新款没有问题。

**Comment by xiaoyang432** [comment]
固件版本： ver-1.0.1-20190726.1122 已经解决

**Comment by fengzehua5** [comment]
问题已解决
