### ISSUE TITLE
推送问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#49]
**问题描述**
APP后台运行及退出都不会收到推送

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
跟推送证书设置有关，之前都是在沙盒环境下测试的，我以后改成生产环境的证书推送证书就能收到了，新版本发布了验证下 @fengzehua5

**Comment by fengzehua5** [comment]
已解决
