### ISSUE TITLE
测试报警

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#50]
**问题描述**
报警器类设备无测试报警按钮

**测试环境**
1. 固件版本号: app-1.0.1-20190627.1638
2. app版本号:FamilyWell+1.0
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60567429-91e9fa00-9d9c-11e9-9826-6ca1d9d1bdac.png)

**Comment by tracyhenryduck2** [comment]
测试报警文字已修正，有个设备老网关可以报警，添加到新的阿里网关无法报警，网关有反馈给app发送成功信息； @xiaoyang432

**Comment by fengzehua5** [comment]
按钮恢复，点击后APP显示发送成功，但是网关和设备无响应

**Comment by xiaoyang432** [comment]
"ver-...20190725..."之后的固件版本，已经解决，3mS不间断广播持续10S。

**Comment by fengzehua5** [comment]
问题已解决
