### ISSUE TITLE
子设备容易出现离线的问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#51]
**问题描述**
基本所有设备在一定的时间里不操作都会离线，插座是无法通过其按钮唤醒的，必须重新添加；场景开关在设备页显示离线，但是进入其子设备页是在线的

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60641938-9c6dc780-9e60-11e9-90f4-023f5b8e56fb.png)
![image](https://user-images.githubusercontent.com/52404201/60641947-a42d6c00-9e60-11e9-9661-7fe4cdff7981.png)
![image](https://user-images.githubusercontent.com/52404201/60641953-abed1080-9e60-11e9-910b-b656741c34bb.png)

**Comment by tracyhenryduck2** [comment]
已解决 @fengzehua5

**Comment by fengzehua5** [comment]
问题仍然存在，Android与iOS都会出现
![image](https://user-images.githubusercontent.com/52404201/61047619-7a50e800-a412-11e9-8755-64dd3c11379b.png)
![image](https://user-images.githubusercontent.com/52404201/61047808-e2073300-a412-11e9-9f9b-0851a5464488.png)

**Comment by tracyhenryduck2** [comment]
这个是插座第一次添加没报状态的问题吧，就是插座组网后的第一个状态肯定是离线 @xiaoyang432 另外情景开关列表和详情页状态不同步的问题还有吗？ @fengzehua5

**Comment by tracyhenryduck2** [comment]
情景开关列表页和详情页状态不一样的问题已解决 @fengzehua5

**Comment by fengzehua5** [comment]
问题在很长时间里没有重现

**Comment by tracyhenryduck2** [comment]
子设备容易出现离线的问题 有没有必要专门开会讨论或者培训一下 @qiubaochun @xiaoyang432

**Comment by xiaoyang432** [comment]
APP显示灰色不代表是离线，以下操作会造成显示灰色：
1.网关重启之后，子设备状态会丢失，如果马上同步会显示离线，需要通过设备心跳包恢复。
2.是否离线，通过推送信息查看，不要简单的看APP灰色就说离线。
