### ISSUE TITLE
APP处于后台时收不到推送消息

### ISSUE THREAD

**Issue by jianlin-wang** [SiterWell01/GS188_ALi#52]
**问题描述**
产品在做测试时发现，当APP处于后台运行且手机界面正常显示，产品报警后，APP有报警声，但是没有推送消息。

**测试环境**
1. 固件版本号: 1.0.3.21
2. app版本号:2.630
3. 其它: 

**截图**

**Comment by xiaoyang432** [comment]
之前的188不在这里讨论
