### ISSUE TITLE
配网失败

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#54]
**问题描述**
Android的配网失败后，点击下面的配网失败原因，由于已经开放了非法字符，里面的“空格问题”应当删除，iOS的配网界面UI需要进行较大的改动与优化

**测试环境**
1. 固件版本号: 
2. app版本号:FamilyWell+1.0   1.004
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60693313-6b4ad100-9f0c-11e9-881a-c5c123030cc9.png)

**Comment by tracyhenryduck2** [comment]
@fengzehua5 这个是软件放开过滤，但是底层由于路由器和设备的硬件兼容性问题，也很可能会导致配网失败，所以这个原因还是得写。

**Comment by fengzehua5** [comment]
空格虽然开放，但是有时会因为空格存在导致的配网失败，所以需要保留
