### ISSUE TITLE
网关添加问题

### ISSUE THREAD

**Issue by Jayce-Poo** [SiterWell01/GS188_ALi#57]
**问题描述**
### IOS
添加网关时，后面的添加按钮点击无反应，点网关栏就可以，这里需要进行修改。
网关添加时，读取进度的UI，需要优化。

**测试环境**
1. 固件版本号: 
2. app版本号:FamilyWell+ 1.0
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
已解决 @Jayce-Poo
