### ISSUE TITLE
温湿度的显示问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#58]
**问题描述**
温湿度探测器显示出现bug

**测试环境**
1. 固件版本号: ver-1.0.1-20190712.0837
2. app版本号:FamilyWell+1.1
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/61101233-964c9c00-a49b-11e9-8144-a607aa73bbfa.png)
![image](https://user-images.githubusercontent.com/52404201/61101242-9c427d00-a49b-11e9-8ba3-aebb72cfd7ac.png)
![image](https://user-images.githubusercontent.com/52404201/61101249-a2385e00-a49b-11e9-98e5-c7f35d388411.png)
![image](https://user-images.githubusercontent.com/52404201/61101254-a82e3f00-a49b-11e9-80e5-a4180b6e305b.png)

**Comment by tracyhenryduck2** [comment]
透传数据记录如下：
00030102045C194E5D29393C
0003010204FF01015D2938DE
0003010203FF01015D2931D8
00030102045C194E5D292C15
0003010203FF01015D292AD1
0003010203FF01015D2923CA
00030102045C194F5D291CCA
0003010203FF01015D291CC3
0003010203FF01015D2915BC
0003010203FF01015D290EB5OVER;

其中确实有0101的数据，说明1摄氏度，%1确实是设备报上来的数据。 @fengzehua5 请联系温湿度传感器开发人员协助解决。

**Comment by fengzehua5** [comment]
单个设备问题，但是在问题持续一周左右之后就一直没有出现此问题，属于个例偶然，建议不做深入研究。
