### ISSUE TITLE
设备页闪退问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#59]
**问题描述**
当添加多个网关时，在设备页展开一个网关的所有设备；下拉到第二个网关，点击展开后，第一个网关的子设备列表会关闭；再次点击第一个网关的展开按钮，APP会闪退；网关的设备展开按钮不易点到，当只添加一个·网关，展开按钮无法点到

**测试环境**
1. 固件版本号: ver-1.0.1-20190712.0837
2. app版本号:FamilyWell+1.1
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
已解决

**Comment by tracyhenryduck2** [comment]
@fengzehua5

**Comment by fengzehua5** [comment]
测试后无问题
