### ISSUE TITLE
自动化中虚拟设备在执行条件中的问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#6]
**问题描述**
编辑自动化时，执行条件里存在虚拟设备，选中“条件全部满足才触发”，此时执行其中一个就会触发，相关的UI需要修改。在适当的地方需要有提示说明。

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
1.009已解决 @fengzehua5

**Comment by fengzehua5** [comment]
已解决
