### ISSUE TITLE
设备页面设备更改

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#60]
**问题描述**
首页的设备长按只可以删除设备，网关页的设备长按无反应

**测试环境**
1. 固件版本号: ver-1.0.1-20190712.0837
2. app版本号:FamilyWell+1.1
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
@fengzehua5 1.5v版本已解决这个问题

**Comment by fengzehua5** [comment]
已解决
