### ISSUE TITLE
网关绑定失败时提示修改

### ISSUE THREAD

**Issue by qiubaochun** [SiterWell01/GS188_ALi#62]
问题描述
绑定失败时，会有弹窗提示：设备已被管理员绑定，请联系管理员解绑或将设备分享给您
          设备已被管理员绑定
请联系管理员解绑或初始化设备
              如何初始化

点击进入网关初始化引导页面

测试环境

固件版本号:
app版本号:1.004
其它:

**Comment by tracyhenryduck2** [comment]
@fengzehua5 ios1.4版本已解决了，安卓还没增加引导页面

**Comment by tracyhenryduck2** [comment]
android 1.009已解决 @fengzehua5

**Comment by fengzehua5** [comment]
已解决
