### ISSUE TITLE
设备页面问题

### ISSUE THREAD

**Issue by Jayce-Poo** [SiterWell01/GS188_ALi#64]
**问题描述**
设备详细页面有空白按键，适配性问题，需要修改。

**测试环境**
1. 固件版本号: 
2. app版本号: FamilyWell+1.1
3. 其它: IOS

**截图**
![微信图片_20190713155316](https://user-images.githubusercontent.com/52475262/61168822-64fcca80-a586-11e9-968d-a4d76575bd53.jpg)

**Comment by qiubaochun** [comment]
问题重复
