### ISSUE TITLE
水感设备的显示问题

### ISSUE THREAD

**Issue by Jayce-Poo** [SiterWell01/GS188_ALi#65]
**问题描述**
1、网关下的水感的状态显示是错误的。显示离线，实际点进去是正常。
2、界面有空白虚拟按键。

**测试环境**
1. 固件版本号: 
2. app版本号:FamilyWell+1.1
3. 其它: 

**截图**
![微信图片_20190713155318](https://user-images.githubusercontent.com/52475262/61168846-b3aa6480-a586-11e9-8ecb-652bcc5e9500.jpg)
![微信图片_20190713155309](https://user-images.githubusercontent.com/52475262/61168863-df2d4f00-a586-11e9-9809-5377a99e21a1.jpg)

**Comment by fengzehua5** [comment]
水感的空白虚拟按钮已经没有了；CO报警器同样在首页和网关页显示离线，在其子设备界面显示在线

**Comment by tracyhenryduck2** [comment]
1.4版本已解决 @Jayce-Poo
