### ISSUE TITLE
网关执行动作问题

### ISSUE THREAD

**Issue by Jayce-Poo** [SiterWell01/GS188_ALi#69]
**请描述你的想法**
网关应该有：
1、危险报警
2、非法闯入
3、静音
4、门铃声（目前不支持）
5、切换到在家/离家/睡眠模式或者自定义的场景（目前没有）
安卓是有的，IOS好像这个一直没有增加。

**Comment by fengzehua5** [comment]
iOS添加自动化时，在执行条件中添加门锁后，执行动作里网关页才会出现场景切换的选项；对于Android，添加门锁后在执行动作里选择网关，点击进入网关页后上拉会闪退

**Comment by tracyhenryduck2** [comment]
1.009已解决这个问题 @fengzehua5

**Comment by fengzehua5** [comment]
已解决
