### ISSUE TITLE
APP切换情景模式同步问题

### ISSUE THREAD

**Issue by jianlin-wang** [SiterWell01/GS188_ALi#70]
**问题描述**
APP在线状态下，前一天晚上手机锁屏（手机不关机），第二天早上手机解锁，APP上的情景模式处于睡眠状态，此时设备的告警信息都不能查看；在管理界面操作产品的下发测试功能无效。需手动更改情景模式。

**测试环境**
1. 固件版本号: 2.0.3.21
2. app版本号:2.633
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
@jianlin-wang Familywell的问题请放在https://github.com/SiterWell01/GS188-Familywell/issues 这里
