### ISSUE TITLE
app主页面显示bug

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#71]
**问题描述**
APP进入主页面后，下拉到列表底部后上拉，温湿度计后面会出现一个插座功能按钮，点击无效
一加手机出现的问题，vivo手机没有

**测试环境**
1. 固件版本号: ver-1.0.1-20190716.1307
2. app版本号:1.006
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/61694360-dc3f1500-ad63-11e9-9302-e99d725bc2f8.png)
![image](https://user-images.githubusercontent.com/52404201/61694380-e4975000-ad63-11e9-9901-39633fbf4c55.png)

**Comment by tracyhenryduck2** [comment]
1.008会修复此bug @fengzehua5

**Comment by fengzehua5** [comment]
已解决
