### ISSUE TITLE
国内版与国际板同时安装后问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#72]
**问题描述**
安卓手机同时安装国内与国际版本的APP，打开其中任意一个软件，都会有弹窗提示选择将要打开的app；在首页点击添加，再点击网关后，也会弹出。

**测试环境**
1. 固件版本号: ver-1.0.1-20190726.1122
2. app版本号:1.007
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/62191909-24cf8180-b3a7-11e9-8de3-0588c366ec62.png)
![image](https://user-images.githubusercontent.com/52404201/62273229-98d55c80-b46f-11e9-813e-674c19ee6e39.png)

**Comment by tracyhenryduck2** [comment]
@fengzehua5  1.008会解决这个bug

**Comment by fengzehua5** [comment]
已解决
