### ISSUE TITLE
数据上报时主页面自动跳转到网关问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#73]
**问题描述**
在首页设备列表展开网关，下拉到网关不显示在屏幕上，触发任意一报警器使得数据上报，此时列表会自动跳转为网关为首的列表情况

**测试环境**
1. 固件版本号: ver-1.0.1-20190805.0844
2. app版本号:1.008
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
1.009将修复这个bug @fengzehua5

**Comment by fengzehua5** [comment]
已解决
