### ISSUE TITLE
新增的四个设备

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#8]
**问题描述**
开光模块和室外警笛的连入网关教程动图现在还没有，门锁的教程动图需要修改

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**
![image](https://user-images.githubusercontent.com/52404201/60560992-99050e00-9d84-11e9-83ba-618c36644984.png)
![image](https://user-images.githubusercontent.com/52404201/60561022-a9b58400-9d84-11e9-9786-b7aa1e110962.png)

**Comment by fengzehua5** [comment]
目前门锁的教程动图在iOS上已更新，Android还没有更新；开关模块与警笛还没有添加

**Comment by fengzehua5** [comment]
iOS已完成，Android还没有

**Comment by fengzehua5** [comment]
Android的门锁动图教程还没有更改，其他全部完成

**Comment by ju0014** [comment]
已修复

**Comment by tracyhenryduck2** [comment]
1.008会修复此bug

**Comment by tracyhenryduck2** [comment]
@fengzehua5

**Comment by fengzehua5** [comment]
已解决
