### ISSUE TITLE
网关配置WiFi界面问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#84]
**问题描述**
配置网关时，打开键盘，配置WiFi界面的路由器SSID和“记住密码”重叠，此时右边的眼睛符号“显示密码”点击无反应。

**测试环境**
1. 固件版本号: ver-1.0.1-20190924.1505
2. app版本号:家庭卫士iOS1.8
3. 其它: 

**截图**
![7F9B02055BC4A9A8163CED46A70D8D0E](https://user-images.githubusercontent.com/52404201/67839608-fe98b980-fb2e-11e9-8246-6dc82de3ca68.JPG)

**Comment by tracyhenryduck2** [comment]
已解决 @fengzehua5

**Comment by fengzehua5** [comment]
已验证，问题已解决
