### ISSUE TITLE
安全评分页自动检测

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#85]
**问题描述**
每次打开app，切换到“安全评分”，会自动检测。一般用户都不会喜欢APP它自己做一些事情，可以改成点击开始测试，长时间不检测会弹窗提示

**测试环境**
1. 固件版本号: ver-1.0.1-20190924.1505
2. app版本号:家庭卫士iOS1.8
3. 其它: 

**截图**

**Comment by tracyhenryduck2** [comment]
已解决 @fengzehua5

**Comment by fengzehua5** [comment]
已解决
