### ISSUE TITLE
加入PIR后的问题

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#9]
**问题描述**
任一场景下添加“默认PIR自动化”，触发PIR后有客户端推送，但是网关无任何动作，之后PIR一直处于触发状态，不会恢复。

**测试环境**
1. 固件版本号: 
2. app版本号:1.004
3. 其它: 

**截图**

**Comment by xiaoyang432** [comment]
网关会报警，之后的版本会解决，PIR设备通讯有很大问题，需要调试7129驱动。

**Comment by xiaoyang432** [comment]
新的PIR没有问题，只是老款PIR有问题，暂时不解决。

**Comment by qiubaochun** [comment]
同#47
