### ISSUE TITLE
网关页按钮重叠

### ISSUE THREAD

**Issue by fengzehua5** [SiterWell01/GS188_ALi#92]
**问题描述**
网关页的设备页“添加设备”与设备功能键（如插座的开关键）会重叠，情景要改为场景，场景也会和“添加场景”重叠

**测试环境**
1. 固件版本号: 
2. app版本号:家庭卫士安卓2.0
3. 其它: 

**截图**

**Comment by javofxu** [comment]
已解决

**Comment by fengzehua5** [comment]
已验证
