### ISSUE TITLE
App中文字错误

### ISSUE THREAD

**Issue by Jayce-Poo** [SiterWell01/GS188_ALi#95]
**问题描述**
FamilyWell、家庭卫士APP的添加设备界面，文字出现错误。。NF设备需要改成RF设备或者子设备

**测试环境**
1. 固件版本号: 和固件无关
2. app版本号:所有版本
3. 其它: 

**截图**
![微信图片_20191114090218](https://user-images.githubusercontent.com/52475262/68817729-95cc4800-06bd-11ea-9de3-36516df084e2.jpg)

**Comment by tracyhenryduck2** [comment]
新版app已经更改了ui，分类方式都不一样了，这个问题已解决 @Jayce-Poo

**Comment by tracyhenryduck2** [comment]
@Jayce-Poo 你测试的是app store上的版本吧，我们内部测试都以内测平台上发布的为准，那个才是最新的

**Comment by fengzehua5** [comment]
已验证，目前UI已更改
